# yolov1
S: 7
B: 2

# Pascal VOC Dataset
input_size: 448
train_path: /home/blattst/git/pizza/dataset/train/
valid_path: /home/blattst/git/pizza/dataset/valid/
test_path: /home/blattst/git/pizza/dataset/test/
# class names
class_names: [ 'Pizza', 'Pepperoni' ]

# training 
batch_size: 32