# yolov1
S: 7
B: 2

# Pascal VOC Dataset
input_size: 448
train_path: /content/Pizza-5/train/
valid_path: /content/Pizza-5/valid/
test_path: /content/Pizza-5/test/
# class names
class_names: [ 'Pizza', 'Pepperoni' ]

# training 
batch_size: 32
